services:
    db:
        image: postgres:15-alpine
        container_name: postgres-db
        restart: always
        environment:
            POSTGRES_DB: cozy_apps
            POSTGRES_USER: postgres_admin
            POSTGRES_PASSWORD: pw123ldascsdcdasdfas
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres_admin -d cozy_apps"]
            interval: 5s
            timeout: 5s
            retries: 10

    api:
        build:
            context: ..
            dockerfile: server/Dockerfile
        container_name: express-api
        restart: always
        ports:
            - "8080:8080"
        env_file:
            - ../.env
        depends_on:
            db:
                condition: service_healthy
        links:
            - db

volumes:
    postgres_data:
