FROM node:20-alpine

WORKDIR /usr/src/app

ENV NODE_ENV=production

COPY package*.json ./

RUN npm ci && npm install -g tsx

COPY tsconfig*.json ./

COPY server/src ./src

EXPOSE 8080

USER node

CMD ["tsx", "src/index.ts"]